### PR TITLE
Use mod.conf for dependencies and description

### PR DESCRIPTION
**Pull request by Panquesito7**
Deletes deprecated `depends.txt` and `description.txt`.

### CODE REVIEW

**Comment by Panquesito7** [comment]
@sofar.

**Comment by SmallJoker** [comment]
Could you please also update the README, so that it states the MInetest 5.0 requirement?

**Comment by Panquesito7** [comment]
Updated.

**Comment by SmallJoker** [comment]
Thanks. Will merge in a few days unless there are objections from @sofar.

**Comment by Panquesito7** [comment]
@SmallJoker.

**Pull request merged**
