### PR TITLE
change digiline to digilines in nodedef

### PR DESCRIPTION
**Pull request by DS-Minetest**
Finally fixes https://github.com/minetest-mods/digilines/pull/44#issuecomment-287105804.

### CODE REVIEW

**Comment by numberZero** [comment]
Acceptable.
Another variant:
```lua
function digilines.getspec(node)
	local nodedef = minetest.registered_nodes[node.name]
	if not nodedef then return false end
	return nodedef.digilines or nodedef.digiline
 end
 ```

**Comment by DS-Minetest** [comment]
Your variant seems to be better since it saves some indexing.

**Comment by DS-Minetest** [comment]
To be reviewed/approved/merged.

**Comment by DS-Minetest** [comment]
This PR does not break anything, is simple, is not controversial and is already here in its current state for over a whole year. Other mods won't update their node specs until this here gets merged.
I think, the maintaining of **minetest-mods**/digilines could be a little bit faster.

**Comment by sofar** [comment]
Next time, please ping me 30 days after a PR is considered ready for merge. I haven't had time to go through all the mods in a while and find these sort of ready-to-go prs and merge them.

**Pull request merged**
