### PR TITLE
Fixed deprecated calls.

### PR DESCRIPTION
**Pull request by EdwardThorsten**

### CODE REVIEW

**Comment by DS-Minetest** [comment]
https://github.com/minetest-mods/mesecons/pull/344#issuecomment-306908127

**Comment by sofar** [comment]
agreed with waiting a few more months. Patch is OK, though.

**Comment by EdwardThorsten** [comment]
Well, I can understand the reasoning. 9/10 linux distro repositories still run old Minetest versions that do not support this yet. Ideally, one could code a simple wrapper (I have seen that trick done in at least one mod...) that makes use of the legacy call if the new one isn't recognized.

My push requests, such as this one, are flying out everywhere as I cleanup the code being imported to my own project. The way this seems to work, if I understand correctly, is that a PR is just a notification for a change somewhere else that _might_ be interesting. In essence it seems to be a way of communication between developers. I'm using it that way, to communicate. I have been doing things hidden in my man cave for too long, and it's time to broaden my horizons. Thanks for bearing with me, as I learn the ropes.

**Comment by SmallJoker** [comment]
Revived by #51

**Pull request closed without merging**
