### PR TITLE
Convert digilines to a mod (not modpack).

### PR DESCRIPTION
**Pull request by sofar**
Digilines is probably used by most people in its entirety.

I've retained the ability to disable inventory, rtc, lightsensor and
LCD by the minetest settings "diglines_enable_rtc" etc.. If set to
"false", these components will not be loaded. It is assumed by default
that these are enabled.

In the conversion the digilines_lcd:lcd node was renamed to
digilines:lcd (same for all the other nodes). To retain backwards
compatibility I've provided aliases for each of these nodes.

### CODE REVIEW

**Comment by sofar** [comment]
Needs testing, please.

**Comment by benrob0329** [comment]
"diglines_enable_rtc = false" doesn't seem to change anything.

**Comment by Jeija** [comment]
I would suggest organizing settings like we have them in mesecons: https://github.com/Jeija/minetest-mod-mesecons/blob/master/mesecons/settings.lua.
This way, all the settings for digilines are structured in `digilines.*`, like `digilines.enable_rtc`. Also, the mesecons model has support for default values and types, so that you can call
`mesecon.setting("timeout_for_something", 100)`. I think it is useful to switch to that model before introducing new settings to digilines.

Here are some other issues I have found while testing your patch:
* Renaming the `digilines_lcd:text` entity to `digilines:text` causes ugly "object not found" entities to appear in front of every LCD. I don't think we can register entity aliases (or can we?), but that entity should at least be removed the next time the display updates.
* The settings don't work for me either, `false` is interpreted as a boolean, so it should be `== false` instead of `== "false"`. Once again, I suggest you to implement a system like in mesecons, which abstracts all that away so that you only need
```Lua
if digiline.setting("enable_rtc", true) then
  -- do something
end
```
* I haven't tested the digiline chest, I haven't ever used that, so I'm propably not the right person to ask :smirk: 

It's great to see some development on digilines, thank you everyone at `minetest-mods`!

**Comment by sofar** [comment]
I don't like doing all the abstracting... it's more lines of code to abstract than to do it right :)

Of course, I did have to fix it so it works. So I've resorted to using `minetest.is_yes()` which works (tested).

I've also reverted the entity name change for the lcd, I'll just keep the old entity name and everything should work as before.

**Pull request merged**
